### PR TITLE
Fixes danielwertheim/mycouch#85.

### PR DESCRIPTION
**Pull request by ncruces**

### CODE REVIEW

**Comment by ncruces** [comment]
Any interest in merging this?

**Comment by danielwertheim** [comment]
Yes. Can do it for v4.

**Comment by danielwertheim** [comment]
Looked at it now, why not something like this instead: https://github.com/danielwertheim/mycouch/commit/9cb74fcdb547092c83665d313c8c53467580b298

`Id` should really have a value when using the `_all_docs` view...

**Comment by danielwertheim** [comment]
This is superseded by the commit linked to above that has a slight change in not to return those rows at all. Released in `v4.0.0-rc3'

**Pull request closed without merging**
